### ISSUE TITLE
有的已结束课程无法下载

### ISSUE THREAD

**Issue by 1160300208** [PyJun/Mooc_Downloader#10]
https://www.icourse163.org/course/JSIT-1001754045?tid=1206614262

**Comment by PyJun** [comment]
用最新版下载器


 
---原始邮件---
发件人: "Li Zhilin"<notifications@github.com&gt;
发送时间: 2020年1月15日 23:00:44
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [PyJun/Mooc_Downloader] 有的已结束课程无法下载 (#10)



https://www.icourse163.org/course/JSIT-1001754045?tid=1206614262

**Comment by 1160300208** [comment]
![image](https://user-images.githubusercontent.com/34236718/72446652-ead82780-37ee-11ea-8d3b-94ab18fc4631.png)
依然无法下载

**Comment by PyJun** [comment]
可以下载，是你的网络问题，建议换一下网




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Li Zhilin"<notifications@github.com&gt;; 
发送时间: 2020年1月15日(星期三) 晚上11:35
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;; 
抄送: "PyJun"<py.jun@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [PyJun/Mooc_Downloader] 有的已结束课程无法下载 (#10)





 依然无法下载
