### ISSUE TITLE
会员能否下载字幕

### ISSUE THREAD

**Issue by linyy815** [PyJun/Mooc_Downloader#102]
能否下载单独的字幕文件。看到隔壁有个软件好像可以，技术上行得通，能否辛苦工程师们辛苦开发下？谢谢哟~~

**Comment by PyJun** [comment]
如果视频待字幕文件，是支持字幕下载的

**Comment by PyJun** [comment]
有些视频是把字幕集成到视频文件里面的，这些课程本来就没有单独的字幕文件，也就没字幕可下

**Comment by linyy815** [comment]
您好，已收到邮件，会尽快给您回复。请静心等待~

**Comment by PyJun** [comment]
字幕文件后缀名是 .srt ，支持用 potplayer 播放器直接打开的

**Comment by linyy815** [comment]
您好，已收到邮件，会尽快给您回复。请静心等待~

**Comment by PyJun** [comment]
支持的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月11日(周二) 下午4:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [PyJun/Mooc_Downloader] 会员能否下载字幕 (Issue #102)




 您好，已收到邮件，会尽快给您回复。请静心等待~
