### ISSUE TITLE
学银在线无法完全下载

### ISSUE THREAD

**Issue by Eric-Sjt** [PyJun/Mooc_Downloader#109]
版本为最新
测试课程为这个http://www.xueyinonline.com/detail/222549124
可能是逻辑上只下载第一个课件

**Comment by baifachuan** [comment]
你还真信这个仓库。。https://mp.weixin.qq.com/s/kAvnFZUMOcSLPaCmP1wsEw

自己去看吧

**Comment by PyJun** [comment]
新版本已经修复这个问题了，请下载新版重试下：
https://pyjun.lanzoui.com/b00n4ln4b
