### ISSUE TITLE
无法下载已结束课程

### ISSUE THREAD

**Issue by Lindsay284** [PyJun/Mooc_Downloader#113]
下载了好几门已结束课程，发现只下载了字幕QAQ，大大有解决方法不

**Comment by PyJun** [comment]
有课程链接吗，应该是可以下载的

**Comment by Lindsay284** [comment]
> 有课程链接吗，应该是可以下载的

你可以随便找一个已结束课程试一下，我试了很多个都不行，只下载到了字幕文件

**Comment by awxiaoxian2020** [comment]
> > 有课程链接吗，应该是可以下载的
> 
> 你可以随便找一个已结束课程试一下，我试了很多个都不行，只下载到了字幕文件

我这边可以

**Comment by baifachuan** [comment]
你们还真信这个仓库啊，自己去看吧https://mp.weixin.qq.com/s/kAvnFZUMOcSLPaCmP1wsEw

**Comment by PyJun** [comment]
中国大学已结束课程，支持下载，其它网站的不支持
