### ISSUE TITLE
新版本代码没开源，可能含有恶意代码

### ISSUE THREAD

**Issue by linonetwo** [PyJun/Mooc_Downloader#116]
会请求管理员权限，而且弹微信扫码。希望能放出源码安心一点。

而且这样有蹭「开源」旗号的嫌疑，浪费大家的 star。

**Comment by PyJun** [comment]
没病毒的，建议把杀毒软件关了，以免误报



---原始邮件---
发件人: "lin ***@***.***&gt;
发送时间: 2022年3月9日(周三) 晚上10:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PyJun/Mooc_Downloader] 新版本代码没开源，可能含有恶意代码 (Issue #116)




 
会请求管理员权限，而且弹微信扫码。希望能放出源码安心一点。
 
而且这样有蹭「开源」旗号的嫌疑，浪费大家的 star。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by swufexym** [comment]
看别人在沙箱运行时软件请求了管理员权限...

**Comment by PyJun** [comment]
这是因为之前有部分用户反馈，需要管理员运权限行，才能使用



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月10日(周四) 凌晨2:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PyJun/Mooc_Downloader] 新版本代码没开源，可能含有恶意代码 (Issue #116)




 
看别人在沙箱运行时软件请求了管理员权限...
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by linonetwo** [comment]
感觉可以除了规则部分代码都放一下，比较会更符合开源一些，保持好风气
