### ISSUE TITLE
只能下课件，并不能下视频

### ISSUE THREAD

**Issue by bigppyy** [PyJun/Mooc_Downloader#121]
![image](https://user-images.githubusercontent.com/101436419/157997245-e1244b51-7e8a-406e-bd18-8c4941b81607.png)

**Comment by PyJun** [comment]
这个版本的太老了，你用 realeases 下面的最新版本

**Comment by PyJun** [comment]
你选择了仅下载课件吧，或者这个课程本来就没视频



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月12日(周六) 上午9:06
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PyJun/Mooc_Downloader] 只能下课件，并不能下视频 (Issue #121)




 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
