### ISSUE TITLE
申请添加视频网站支持

### ISSUE THREAD

**Issue by awxiaoxian2020** [PyJun/Mooc_Downloader#122]
http://video.chaoxing.com/

**Comment by baifachuan** [comment]
你还真信这个仓库啊，https://mp.weixin.qq.com/s/kAvnFZUMOcSLPaCmP1wsEw
自己去看吧

**Comment by awxiaoxian2020** [comment]
> 你还真信这个仓库啊，https://mp.weixin.qq.com/s/kAvnFZUMOcSLPaCmP1wsEw 自己去看吧

作者已在readme文档中告知，开源项目不再维护。鉴于该项目的特殊性，我理解作者无法继续开源。但是这不影响我提这个issue。我个人认为就这篇文章中所披露的事实不足以到你“吸血”的说法。当然，我也没有必要纠结你的看法。
我认为你就算要与违背开源精神的行为作斗争，也不要用这种语气：
> GitHub is a global community with people from a wide variety of backgrounds and perspectives, many of which may not be your own. Try to put yourself in others’ shoes and understand their feelings before you address them. Do your best to help make GitHub a community where others feel safe to make contributions, participate in discussions, and share different ideas.

> While some disagreements can be resolved with direct, respectful communication between community members, we understand that is not always the case. We encourage our community to [let us know](https://support.github.com/contact/report-abuse?category=report-abuse&report=other&report_type=unspecified) when they believe content or activity they’ve encountered violates our policies. However, if you run into something or someone on the site that you find objectionable, here are some ways GitHub enables you to take action...

**Comment by PyJun** [comment]
已支持超星学习通

**Comment by awxiaoxian2020** [comment]
> 已支持超星学习通

不是经典的超星学习通，你打开看一下

**Comment by PyJun** [comment]
加下QQ群:&nbsp;196020837
方便反馈问题



---原始邮件---
发件人: "Xavi ***@***.***&gt;
发送时间: 2022年6月7日(周二) 下午2:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PyJun/Mooc_Downloader] 申请添加视频网站支持 (Issue #122)




  
已支持超星学习通
  
不是经典的超星学习通，你打开看一下
