### ISSUE TITLE
请遵守 aria2 开源协议

### ISSUE THREAD

**Issue by amakerlife** [PyJun/Mooc_Downloader#132]
本项目下载功能调用 aria2，aria2 开源协议为 GPL2.0，在该协议中，明确表明修改源码后必须开源，但本项目源码已停止维护；明确表明新增的代码需采用同样许可证，但本项目为 None License。

https://github.com/aria2/aria2/blob/f4cbc7bb315b1687679e6ab94648c2685a9e9668/COPYING#L79-L112

**Comment by PyJun** [comment]
直接用的exe，没有修改aria2源代码



---原始邮件---
发件人: "Yuyang ***@***.***&gt;
发送时间: 2023年1月29日(周日) 晚上6:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PyJun/Mooc_Downloader] 请遵守 aria2 开源协议 (Issue #132)




 
本项目下载功能调用 aria2，aria2 开源协议为 GPL2.0，在该协议中，明确表明修改源码后必须开源，但本项目源码已停止维护；明确表明新增的代码需采用同样许可证，但本项目为 None License。
 
https://github.com/aria2/aria2/blob/f4cbc7bb315b1687679e6ab94648c2685a9e9668/COPYING#L79-L112

**Comment by amakerlife** [comment]
> 直接用的exe，没有修改aria2源代码
> […](#)
> ---原始邮件--- 发件人: "Yuyang ***@***.***&gt; 发送时间: 2023年1月29日(周日) 晚上6:32 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [PyJun/Mooc_Downloader] 请遵守 aria2 开源协议 (Issue #132) 本项目下载功能调用 aria2，aria2 开源协议为 GPL2.0，在该协议中，明确表明修改源码后必须开源，但本项目源码已停止维护；明确表明新增的代码需采用同样许可证，但本项目为 None License。 https://github.com/aria2/aria2/blob/f4cbc7bb315b1687679e6ab94648c2685a9e9668/COPYING#L79-L112 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

请阅读第一条

https://github.com/aria2/aria2/blob/f4cbc7bb315b1687679e6ab94648c2685a9e9668/COPYING#L79-L85

**Comment by amakerlife** [comment]
另外这个软件使用了好多开源软件但没有声明。

![image](https://user-images.githubusercontent.com/64350662/215321263-ec5513a5-0a2f-44b4-9993-2376d90e74f6.png)

等会吃完饭把这些开源协议都看一遍

另外，我是 annie(现 lux) 的贡献者之一，软件中`优酷,抖音,腾讯,爱奇艺,微博视频,好看视频,芒果TV`的下载不出意外应该是使用 lux

**Comment by amakerlife** [comment]
你至少违反了 aria2, ffmpeg, wkhtmltopdf 的开源协议

**Comment by PyJun** [comment]
已邀请你加入 collaborators，如有不妥之处你可以维护该仓库

**Comment by ZhiShengYuan** [comment]
> 

Please,In any case, please take into account the terms of the relevant agreement for commercial use

**Comment by amakerlife** [comment]
> > 
> 
> Please,In any case, please take into account the terms of the relevant agreement for commercial use

目前来看貌似没有用限制商业使用的项目

**Comment by amakerlife** [comment]
> 已邀请你加入 collaborators，如有不妥之处你可以维护该仓库

我都没有你代码我维护什么啊……

**Comment by amakerlife** [comment]
先别急着 close 啊 @PyJun

**Comment by hokaso** [comment]
> 先别急着 close 啊 @PyJun

叫个屁，版权小子真牛逼啊，人家用的是打包好的二进制文件，用命令行的模式来调用的，根本不涉及你爹制定的 GPL2.0

**Comment by amakerlife** [comment]
> > 先别急着 close 啊 @PyJun
> 
> 叫个屁，版权小子真牛逼啊，人家用的是打包好的二进制文件，用命令行的模式来调用的，根本不涉及你爹制定的 GPL2.0

https://github.com/aria2/aria2/blob/f4cbc7bb315b1687679e6ab94648c2685a9e9668/COPYING#L134C1-L154C1
