### ISSUE TITLE
如何才能正确卸载软件

### ISSUE THREAD

**Issue by ruqing00** [PyJun/Mooc_Downloader#133]
该软件安装完成之后，会在桌面新建一个快捷方式，然后在安装目录是一个名为“LEL-Downloader”的文件夹。
但是我在Windows自带的软件管理工具中并未找到该软件，且使用第三方的软件管理工具也无法看到该软件。
请问如果我要卸载该软件的话，是直接将整个“LEL-Downloader”文件夹删除吗？

**Comment by PyJun** [comment]
> 该软件安装完成之后，会在桌面新建一个快捷方式，然后在安装目录是一个名为“LEL-Downloader”的文件夹。 但是我在Windows自带的软件管理工具中并未找到该软件，且使用第三方的软件管理工具也无法看到该软件。 请问如果我要卸载该软件的话，是直接将整个“LEL-Downloader”文件夹删除吗？

是的
