### ISSUE TITLE
开始收费了，还有免费版本吗？

### ISSUE THREAD

**Issue by daniel-zou** [PyJun/Mooc_Downloader#139]
只能试用，下载一个章节。果然，天下没有免费的午餐

**Comment by PyJun** [comment]
> 只能试用，下载一个章节。果然，天下没有免费的午餐

下载一个课程才一块钱，就当个打赏呗，老板~

**Comment by daniel-zou** [comment]
不是钱的问题。我也知道开发个好用的东西不容易，要点支持是合理的，你可以把收款二维码贴出来，我马上支持。可是，这种会员模式的收费，见过太多了，特别反感，尤其腾讯爱奇艺这种不给钱就不让看的，我从来不充会员，宁可不看。以前是开源免费的工具，现在收费方了，幕客官方可能就会有想法，就可能找你麻烦，收文件，请喝茶一类的。官方随便一个修改，软件可能就不能再用，我还是找其他渠道吧。
