### ISSUE TITLE
是否可以在第一个界面中加入可以修改保存下载文件位置的选项？

### ISSUE THREAD

**Issue by dearsn** [PyJun/Mooc_Downloader#14]
默认是c盘，但是有些人c盘空间并不是很大，而下载的视频文件则有时动辄数十G。
是不可以将第一个界面中的“输入一个视频课程网址(q退出):”改为“输入一个视频课程网址(m输入文件保存位置，q退出):”。并加入修改保存位置逻辑。
我对pythony一窍不通，希望哪位大牛能加入这一功能。先谢过了。

**Comment by PyJun** [comment]
这个建议很好


 
---原始邮件---
发件人: "dearsn"<notifications@github.com&gt;
发送时间: 2020年2月19日 12:32:59
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [PyJun/Mooc_Downloader] 是否可以在第一个界面中加入可以修改保存下载文件位置的选项？ (#14)



默认是c盘，但是有些人c盘空间并不是很大，而下载的视频文件则有时动辄数十G。
 是不可以将第一个界面中的“输入一个视频课程网址(q退出):”改为“输入一个视频课程网址(m输入文件保存位置，q退出):”。并加入修改保存位置逻辑。
 我对pythony一窍不通，希望哪位大牛能加入这一功能。先谢过了。
