### ISSUE TITLE
有没有配置代理的功能？

### ISSUE THREAD

**Issue by jsyanyang** [PyJun/Mooc_Downloader#140]
公司的网络可能对一些网站有限制，开了代理就不会，软件有没有配置代理的地方？已打开就提示网络连接错误

**Comment by PyJun** [comment]
开vpn的时候，选择绕过中国大陆，别开全局模式




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PyJun/Mooc_Downloader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月17日(星期一) 上午10:58
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PyJun/Mooc_Downloader] 有没有配置代理的功能？ (Issue #140)





 
公司的网络可能对一些网站有限制，开了代理就不会，软件有没有配置代理的地方？已打开就提示网络连接错误
