### ISSUE TITLE
Linux下运行该程序的办法：

### ISSUE THREAD

**Issue by cathaysia** [PyJun/Mooc_Downloader#15]
由于本人的系统时linux，所以找到想办法把这个程序在Linux上跑了起来。
首先要安装aria2，然后进入项目目录，执行以下命令：

```shell
rm Mooc/aria2c.exe
ln -s /usr/bin/aria2c Mooc/aria2c.exe
```
下载完成后可能会提示出错，但是应该是应为部分命令在Linux下不支持（比如cls），实际上下载没问题。

> 如果上面的方法不可用，可以尝试把Mooc.spec下的`Mooc\aria2c.exe`替换为`/usr/bin/aria2c`。由于代码没研读，这个文件中的`datas`这个数组不知道是干什么的。

**Comment by PyJun** [comment]
不支持Linux😂

---原始邮件---
发件人: "dragonWater"<notifications@github.com&gt;
发送时间: 2020年2月26日(周三) 下午5:42
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [PyJun/Mooc_Downloader] Linux下运行该程序的办法： (#15)



由于本人的系统时linux，所以找到想办法把这个程序在Linux上跑了起来。
 首先要安装aria2，然后进入项目目录，执行以下命令：
 rm Mooc/aria2c.exe ln -s /usr/bin/aria2c Mooc/aria2c.exe
 
下载完成后可能会提示出错，但是应该是应为部分命令在Linux下不支持（比如cls），实际上下载没问题。
  
如果上面的方法不可用，可以尝试把Mooc.spec下的Mooc\aria2c.exe替换为/usr/bin/aria2c。由于代码没研读，这个文件中的datas这个数组不知道是干什么的。

**Comment by cathaysia** [comment]
整个项目就aria2c.exe这个地方时win和linux不兼容的，给aria2c创建一个软链接就可以啦。

**Comment by How-invin** [comment]
在Mooc_Config.py内
改源码，如下：
#aira2_cmd = '%s -x 16 -s 64 -j 64 -k 2M --disk-cache 128M --max-overall-download-limit %s "{url:}" -d "{dirname:}" -o "{filename:}"'%(aria2_path, download_speed)
aira2_cmd = '%s -x 16 -s 64 -j 64 -k 2M --disk-cache 128M --max-overall-download-limit %s "{url:}" -d "{dirname:}" -o "{filename:}"'%("aria2c", download_speed)
顺便把下载速度提高一下：
download_speed = "4800K"
效果如下（Manjaro）：
![Screenshot_20200329_100151](https://user-images.githubusercontent.com/41119059/77838241-ada3f480-71a4-11ea-9231-f0b41b04b871.png)

**Comment by PyJun** [comment]
可以的，源码研究的不错


 
---原始邮件---
发件人: "Hi"<notifications@github.com&gt;
发送时间: 2020年3月29日 10:05:03
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "PyJun"<py.jun@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [PyJun/Mooc_Downloader] Linux下运行该程序的办法： (#15)




 
在Mooc_Config.py内
 改源码，如下：
 #aira2_cmd = '%s -x 16 -s 64 -j 64 -k 2M --disk-cache 128M --max-overall-download-limit %s "{url:}" -d "{dirname:}" -o "{filename:}"'%(aria2_path, download_speed)
 aira2_cmd = '%s -x 16 -s 64 -j 64 -k 2M --disk-cache 128M --max-overall-download-limit %s "{url:}" -d "{dirname:}" -o "{filename:}"'%("aria2c", download_speed)
 顺便把下载速度提高一下：
 download_speed = "4800K"
 效果如下（Manjaro）：

**Comment by How-invin** [comment]
再送一条linux命令：（在下载好的文件目录下运行）
mkdir pdf; find . -name "*.pdf" | xargs -I '{}' cp '{}' ./pdf
提取出pdf文件

**Comment by zdmgmail** [comment]
> 再送一条linux命令：（在下载好的文件目录下运行）
> mkdir pdf; find . -name "*.pdf" | xargs -I '{}' cp '{}' ./pdf
> 提取出pdf文件

我这里下载 有的视频只下载了pdf, mp4没提示出来

 有的视频pdf也能成功 但视频显示 ： [mp4] 资源无法下载 

系统是
```
uname -a
Linux ar 5.6.3-arch1-1 #1 SMP PREEMPT Wed, 08 Apr 2020 07:47:16 +0000 x86_64 GNU/Linux
```

请问有办法吗

**Comment by zdmgmail** [comment]
https://github.com/PyJun/Mooc_Downloader/issues/25 这里有另一个方案 有的视频可以下载
有的不报错 但只下载了pdf

**Comment by LDONT** [comment]
> 在Mooc_Config.py内
> 改源码，如下：
> #aira2_cmd = '%s -x 16 -s 64 -j 64 -k 2M --disk-cache 128M --max-overall-download-limit %s "{url:}" -d "{dirname:}" -o "{filename:}"'%(aria2_path, download_speed)
> aira2_cmd = '%s -x 16 -s 64 -j 64 -k 2M --disk-cache 128M --max-overall-download-limit %s "{url:}" -d "{dirname:}" -o "{filename:}"'%("aria2c", download_speed)
> 顺便把下载速度提高一下：
> download_speed = "4800K"
> 效果如下（Manjaro）：
> ![Screenshot_20200329_100151](https://user-images.githubusercontent.com/41119059/77838241-ada3f480-71a4-11ea-9231-f0b41b04b871.png)

按照你的方法，pdf可以下载，但是MP4显示资源无法下载呢，而且还有一些MP4解析不到，请问是还做了别的改动吗？

**Comment by How-invin** [comment]
> > 在Mooc_Config.py内
> > 改源码，如下：
> > #aira2_cmd = '%s -x 16 -s 64 -j 64 -k 2M --disk-cache 128M --max-overall-download-limit %s "{url:}" -d "{dirname:}" -o "{filename:}"'%(aria2_path, download_speed)
> > aira2_cmd = '%s -x 16 -s 64 -j 64 -k 2M --disk-cache 128M --max-overall-download-limit %s "{url:}" -d "{dirname:}" -o "{filename:}"'%("aria2c", download_speed)
> > 顺便把下载速度提高一下：
> > download_speed = "4800K"
> > 效果如下（Manjaro）：
> > ![Screenshot_20200329_100151](https://user-images.githubusercontent.com/41119059/77838241-ada3f480-71a4-11ea-9231-f0b41b04b871.png)
> 
> 按照你的方法，pdf可以下载，但是MP4显示资源无法下载呢，而且还有一些MP4解析不到，请问是还做了别的改动吗？

这个可能是程序和Mooc之间处理的问题，部分课程的视频可我也下不了。
