### ISSUE TITLE
vip有其他功能还是只是下载速度快了

### ISSUE THREAD

**Issue by gudukuaile** [PyJun/Mooc_Downloader#17]
vip有没有其他的功能？
还是单纯的下载不限速。

**Comment by banjiaojuhao** [comment]
解除速度限制

**Comment by PyJun** [comment]
> vip有没有其他的功能？
> 还是单纯的下载不限速。

Vip 功能：
1. 支持无限速下载
2. 支持单独下载课件
3. 支持多窗口同时下载

**Comment by PyJun** [comment]
> vip有没有其他的功能？
> 还是单纯的下载不限速。

Vip 功能：
1.  支持无限速下载
2.  支持单独下载课件
3.  支持多窗口同时下载

SVIP 功能：
1. 支持 VIP 的所有功能
2. 支持登录下载已购买课程

**Comment by twitf** [comment]
都有钱买了 还下载个锤锤

**Comment by twitf** [comment]
node.js,electron,crypto-js,aria2, wkhtmltopdf,ffmpeg 为啥不注明使用呢
