### ISSUE TITLE
大神好，win10 64位双击1.51版快捷方式后闪过界面就结束了，请问有哪些可能原因，谢谢！

### ISSUE THREAD

**Issue by jliveusa** [PyJun/Mooc_Downloader#19]

**Comment by PyJun** [comment]
重新下载，重新安装，试下



---原始邮件---
发件人: "jliveusa"<notifications@github.com&gt;
发送时间: 2020年3月20日(周五) 晚上6:40
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [PyJun/Mooc_Downloader] 大神好，win10 64位双击1.51版快捷方式后闪过界面就结束了，请问有哪些可能原因，谢谢！ (#19)

**Comment by PyJun** [comment]
> 重新下载，重新安装，试下
> […](#)
> ---原始邮件--- 发件人: "jliveusa"<notifications@github.com&gt; 发送时间: 2020年3月20日(周五) 晚上6:40 收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [PyJun/Mooc_Downloader] 大神好，win10 64位双击1.51版快捷方式后闪过界面就结束了，请问有哪些可能原因，谢谢！ (#19) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

用最新版
