### ISSUE TITLE
拿pyqt加一个GUI

### ISSUE THREAD

**Issue by ZhaoQi99** [PyJun/Mooc_Downloader#2]

**Comment by PyJun** [comment]
是的，正在考虑加一个UI

**Comment by 1160300208** [comment]
@PyJun 建议在GUI里面对课件加上可选项，不想下载全部课件（有的已经看过有的太简单）

**Comment by ZhaoQi99** [comment]
噫噫噫~感觉我可以拿C#重构一版带GUI的~有时间再搞趴~hhh

**Comment by PyJun** [comment]
> 噫噫噫~感觉我可以拿C#重构一版带GUI的~~有时间再搞趴~hhh

可以啊，欢迎加入~hh
