### ISSUE TITLE
学堂在线还是下载不了

### ISSUE THREAD

**Issue by bluesky-024** [PyJun/Mooc_Downloader#20]
用最新1.5.2版本下载学堂在线时，弹出登陆对话框，但对话框是空白，无任何显示

**Comment by PyJun** [comment]
等待加载会儿，或者重试


 
---原始邮件---
发件人: "bluesky-024"<notifications@github.com&gt;
发送时间: 2020年3月23日 10:21:25
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [PyJun/Mooc_Downloader] 学堂在线还是下载不了 (#20)




 
用最新1.5.2版本下载学堂在线时，弹出登陆对话框，但对话框是空白，无任何显示

**Comment by bluesky-024** [comment]
等了一个小时还是没有显示，重试也是一样，

**Comment by PyJun** [comment]
你电脑是win10还是win7的，几位的，登录那块能发一下截图吗


 
---原始邮件---
发件人: "bluesky-024"<notifications@github.com&gt;
发送时间: 2020年3月23日 12:14:50
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "PyJun"<py.jun@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [PyJun/Mooc_Downloader] 学堂在线还是下载不了 (#20)




 
等了一个小时还是没有显示，重试也是一样，

**Comment by bluesky-024** [comment]
win8，64位

**Comment by bluesky-024** [comment]
显示界面如附件所示

**Comment by bluesky-024** [comment]
![Snap1](https://user-images.githubusercontent.com/62529141/77283986-99757880-6d08-11ea-8cf5-c4daf3e4d4ab.jpg)

**Comment by PyJun** [comment]
估计是系统不谦容，居然还有win8，你换成win10或者win7应该就可以了
 
---原始邮件---
发件人: "bluesky-024"<notifications@github.com&gt;
发送时间: 2020年3月23日 13:08:55
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "PyJun"<py.jun@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [PyJun/Mooc_Downloader] 学堂在线还是下载不了 (#20)




 
win8，64位

**Comment by xiaohanfeidao** [comment]
学堂在线的链接谁能发我一个 老是提示链接不合法
