### ISSUE TITLE
学堂在线的一些需登录下载的课程字幕无法下载下来

### ISSUE THREAD

**Issue by laraon** [PyJun/Mooc_Downloader#21]
尤其是有中文和英文两种字幕的那种，譬如MIT的概率论等等

**Comment by PyJun** [comment]
只能下载一个其中一个字幕




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"laraon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月23日(星期一) 晚上9:53
收件人:&nbsp;"PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[PyJun/Mooc_Downloader] 学堂在线的一些需登录下载的课程字幕无法下载下来 (#21)





 
尤其是有中文和英文两种字幕的那种，譬如MIT的概率论等等

**Comment by laraon** [comment]
字幕只能下载一部分，有些则无法下载下来。上面的MIT的概率论就只能下载部分字幕（譬如1.2节的字幕能下载下来，但1.3节的字幕则下载不下来），并不是所有的字幕都能下载下来呢。

**Comment by PyJun** [comment]
你用的是V1.5.2版本吗，如果是的话，发一个课程链接



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "laraon"<notifications@github.com&gt;; 
发送时间: 2020年3月23日(星期一) 晚上11:12
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;; 
抄送: "PyJun"<py.jun@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [PyJun/Mooc_Downloader] 学堂在线的一些需登录下载的课程字幕无法下载下来 (#21)





 
字幕只能下载一部分，有些则无法下载下来。上面的MIT的概率论就只能下载部分字幕（譬如1.2节的字幕能下载下来，但1.3节的字幕则下载不下来），并不是所有的字幕都能下载下来呢。

**Comment by laraon** [comment]
是1.52版本。且入vip了
https://next.xuetangx.com/course/MITX07011000210/3945253

**Comment by PyJun** [comment]
第三节本来就没字幕，没毛病！






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "laraon"<notifications@github.com&gt;; 
发送时间: 2020年3月23日(星期一) 晚上11:12
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;; 
抄送: "PyJun"<py.jun@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [PyJun/Mooc_Downloader] 学堂在线的一些需登录下载的课程字幕无法下载下来 (#21)





 
字幕只能下载一部分，有些则无法下载下来。上面的MIT的概率论就只能下载部分字幕（譬如1.2节的字幕能下载下来，但1.3节的字幕则下载不下来），并不是所有的字幕都能下载下来呢。

**Comment by laraon** [comment]
不是没字幕，是只有英文字幕。有的中文和英文字幕都有。可能是因为这个原因。
