### ISSUE TITLE
下载有数学公式的课件中很多乱码

### ISSUE THREAD

**Issue by SomaHaruto** [PyJun/Mooc_Downloader#22]
下载爱课程的一些数学物理课程的课件，PDF文档中排版乱掉了，而且公式满是乱码，加载不出来

**Comment by banjiaojuhao** [comment]
看源代码，PDF也是用aria2下载的，应该不会出问题。你可以提供一下出错的url和pdf地址。

**Comment by SomaHaruto** [comment]
比如说爱课程的量子力学http://www.icourses.cn/sCourse/course_3570.html和数值计算方法http://www.icourses.cn/sCourse/course_3756.html
原课件是PPT格式是正常的如附件图1（https://resx.icourses.cn/share/ppt/ppt2/a40993e221836703af349d4314e9a342/201211/127290_0d933e4978d7a1c203bb46737131b614_20121123092946.ppt）
以及下载器下载的PDF显示如附件图2、图3









------------------&nbsp;原始邮件&nbsp;------------------
发件人: "harry huang"<notifications@github.com&gt;; 
发送时间: 2020年7月1日(星期三) 中午1:07
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;; 
抄送: "奇奇"<657137385@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PyJun/Mooc_Downloader] 下载有数学公式的课件中很多乱码 (#22)





 
看源代码，PDF也是用aria2下载的，应该不会出问题。你可以提供一下出错的url和pdf地址。
