### ISSUE TITLE
你好，只能下载PDF是什么问题?

### ISSUE THREAD

**Issue by Fafa-DL** [PyJun/Mooc_Downloader#23]
地址：https://www.icourse163.org/learn/XUST-1206363802?tid=1206674203
只能下载PDF而无法下载视频，请问是什么原因呢？

**Comment by PyJun** [comment]
用最新版本



---原始邮件---
发件人: "Fafa-DL"<notifications@github.com&gt;
发送时间: 2020年3月28日(周六) 下午2:15
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [PyJun/Mooc_Downloader] 你好，只能下载PDF是什么问题? (#23)




 
Closed #23.
