### ISSUE TITLE
v1.6.0 windows defender 报木马

### ISSUE THREAD

**Issue by capitalwell** [PyJun/Mooc_Downloader#24]
v1.6.0 windows defender 报木马病毒，而 v1.5.1  windows defender 不会报毒。
![v1 6windef](https://user-images.githubusercontent.com/22556759/79072442-a2f46e00-7d13-11ea-9e0f-cec97eabb5ef.PNG)

**Comment by PyJun** [comment]
win10更新了吧?
软件不可能有木马



---原始邮件---
发件人: "capitalwell"<notifications@github.com&gt;
发送时间: 2020年4月12日(周日) 晚上11:19
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [PyJun/Mooc_Downloader] v1.6.0 windows defender 报木马 (#24)




 
v1.6.0 windows defender 报木马病毒，而 v1.5.1  windows defender 不会报毒。

**Comment by PyJun** [comment]
应该是安装包的问题，我重新打包了一下，这回没问题了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"capitalwell"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月12日(星期天) 晚上11:19
收件人:&nbsp;"PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[PyJun/Mooc_Downloader] v1.6.0 windows defender 报木马 (#24)





 
v1.6.0 windows defender 报木马病毒，而 v1.5.1  windows defender 不会报毒。

**Comment by xiaoyaoyuxin** [comment]
误报确实有，我在360上也遇到了，不过选信任就OK了。
