### ISSUE TITLE
Linux下可用，多线程下载工具 

### ISSUE THREAD

**Issue by lldxflwb** [PyJun/Mooc_Downloader#25]
### 首先安装工具axel
centos 安装 `yum install axel`
ubuntu 安装'sudo apt install axel'
### 这个是什么？
axel是一个强大的多线程下载工具
### 为什么不用wget，是不是看不起它？
我先把你们要吐的槽给吐了，哈哈哈，并非是看不起它，而是用它的时候报文件名过长，我就算是指定了本地文件名也是不行的。所以换了一个下载工具，大功告成
### 源文件内容更改
当你git clone成功过后，进入到该文件
`cd ./Mooc_Downloader`
`wget -c https://olaindex.lldxgo.com/show/toolP/Mooc_Download.py`
`cp Mooc_Download.py Mooc/Mooc_Download.py`
`rm -f Mooc_Download.py`
就修改完成了
### 后记
不过这样的话，就丢掉了下载状态信息等，也就是说你下载失败了要继续要在，得从头开始下载，不过我能用了，就不改了
不过linux版本就这样，有些解析不出来，还是却大家下exe版本的，嘿嘿。
有问题可以入群讨论，就这个大群咳咳

**Comment by hayschan** [comment]
MacOS 呢？有什么建议吗

**Comment by PyJun** [comment]
目前的办法是开一个windows的虚拟机，Mac后续会支持的



---原始邮件---
发件人: "Hays Chan"<notifications@github.com&gt;
发送时间: 2020年6月9日(周二) 晚上8:18
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [PyJun/Mooc_Downloader] Linux下可用，多线程下载工具  (#25)




 
MacOS 呢？有什么建议吗

**Comment by lldxflwb** [comment]
> ？

brew install axel
macos的brew是个强大的包管理器，主要是这个东西是python所以只是指定下载器而已，很简单。只不过，这个是一个很老版本的python开源了，很多地方都有问题~这边建议虚拟机
