### ISSUE TITLE
希望加个imooc下载

### ISSUE THREAD

**Issue by fungaegis** [PyJun/Mooc_Downloader#27]
https://halo.cyblogs.top/archives/decrypt-imooc-video-download.html
以上是解密教程

**Comment by PyJun** [comment]
多谢分享


 
---原始邮件---
发件人: "fungaegis"<notifications@github.com&gt;
发送时间: 2020年4月16日 23:02:05
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [PyJun/Mooc_Downloader] 希望加个imooc下载 (#27)




 
https://halo.cyblogs.top/archives/decrypt-imooc-video-download.html
 以上是解密教程

**Comment by PyJun** [comment]
> https://halo.cyblogs.top/archives/decrypt-imooc-video-download.html
> 以上是解密教程

你好，现在已经支持 imooc 了
