### ISSUE TITLE
调用aria2返回22错误吗

### ISSUE THREAD

**Issue by JerryZhao-o** [PyJun/Mooc_Downloader#28]
![WeChat305e22926ad71d71d552f335bd134517](https://user-images.githubusercontent.com/43411963/79688932-38e44780-8284-11ea-8233-0256b8048984.png)
### 是不是icourse163屏蔽了aria2， 为什么我运行mooc_downloader http状态码status=403 然后aria2返回22，mooc_downloader就说无法下载资源。

**Comment by JerryZhao-o** [comment]
![image](https://user-images.githubusercontent.com/43411963/79689276-2f5bdf00-8286-11ea-88bd-1ed983f8d5ce.png)

**Comment by JerryZhao-o** [comment]
![image](https://user-images.githubusercontent.com/43411963/79689291-561a1580-8286-11ea-8608-86d1dd6152fa.png)
![image](https://user-images.githubusercontent.com/43411963/79689297-6a5e1280-8286-11ea-867a-dc6f1e47c9fa.png)
![image](https://user-images.githubusercontent.com/43411963/79689328-a3968280-8286-11ea-818d-1244294c42c8.png)

换了其他的课， 只能下载下来部分字幕和pdf 视频一个也没有成功

**Comment by SupremeWolf** [comment]
传给aria2的参数里面加上UA

**Comment by banjiaojuhao** [comment]
付费打赏作者获取技术支持，或者加入我的[fork](https://github.com/banjiaojuhao/Mooc_Downloader-NoSpeedLimit)用爱发电。
该问题已在fork中解决
