### ISSUE TITLE
为什么已经开课的内容，提示没有开课啊，这应该是一个BUG吧，希望楼主更新解决下

### ISSUE THREAD

**Issue by axushilong** [PyJun/Mooc_Downloader#3]
![图片](https://user-images.githubusercontent.com/20788225/60930235-4e851380-a2e7-11e9-8948-89e1edf3ed25.png)
![图片](https://user-images.githubusercontent.com/20788225/60930249-5e9cf300-a2e7-11e9-9c18-19b594901383.png)
为什么已经开课的内容，提示没有开课啊，这应该是一个BUG吧，希望楼主更新解决下，增加下可以选第几次开课的内容下载

**Comment by PyJun** [comment]
有问题加群吧，它指的是第二次的还未开课，下载第一次得用链接下载


 
---原始邮件---
发件人: "许实龙"<notifications@github.com>
发送时间: 2019年7月10日 07:52:32
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [PyJun/Mooc_Downloader] 为什么已经开课的内容，提示没有开课啊，这应该是一个BUG吧，希望楼主更新解决下 (#3)




 
 为什么已经开课的内容，提示没有开课啊，这应该是一个BUG吧，希望楼主更新解决下，增加下可以选第几次开课的内容下载

**Comment by axushilong** [comment]
用链接了，提示找不到，你可以试下看看






在 2019-07-10 07:55:36，"PyJun" <notifications@github.com> 写道：
有问题加群吧，它指的是第二次的还未开课，下载第一次得用链接下载



---原始邮件---
发件人: "许实龙"<notifications@github.com>
发送时间: 2019年7月10日 07:52:32
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [PyJun/Mooc_Downloader] 为什么已经开课的内容，提示没有开课啊，这应该是一个BUG吧，希望楼主更新解决下 (#3)





为什么已经开课的内容，提示没有开课啊，这应该是一个BUG吧，希望楼主更新解决下，增加下可以选第几次开课的内容下载

**Comment by PyJun** [comment]
有问题加群，方便交流




------------------ 原始邮件 ------------------
发件人: "许实龙"<notifications@github.com>;
发送时间: 2019年7月10日(星期三) 晚上10:16
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com>;
抄送: "PyJun"<py.jun@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [PyJun/Mooc_Downloader] 为什么已经开课的内容，提示没有开课啊，这应该是一个BUG吧，希望楼主更新解决下 (#3)



用链接了，提示找不到，你可以试下看看
 
 
 
 
 
 
 在 2019-07-10 07:55:36，"PyJun" <notifications@github.com> 写道：
 有问题加群吧，它指的是第二次的还未开课，下载第一次得用链接下载
 
 
 
 ---原始邮件---
 发件人: "许实龙"<notifications@github.com>
 发送时间: 2019年7月10日 07:52:32
 收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com>;
 抄送: "Subscribed"<subscribed@noreply.github.com>;
 主题: [PyJun/Mooc_Downloader] 为什么已经开课的内容，提示没有开课啊，这应该是一个BUG吧，希望楼主更新解决下 (#3)
 
 
 
 
 
 为什么已经开课的内容，提示没有开课啊，这应该是一个BUG吧，希望楼主更新解决下，增加下可以选第几次开课的内容下载
