### ISSUE TITLE
有没有把icve智慧云教收入囊中的想法💡呢。需求也是很大的。

### ISSUE THREAD

**Issue by jnwxc010** [PyJun/Mooc_Downloader#30]

**Comment by PyJun** [comment]
有时间会考虑等的



---原始邮件---
发件人: "jnwxc010"<notifications@github.com&gt;
发送时间: 2020年4月30日(周四) 凌晨1:07
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [PyJun/Mooc_Downloader] 有没有把icve智慧云教收入囊中的想法呢。需求也是很大的。 (#30)

**Comment by PyJun** [comment]
软件已支持智慧职教下载
