### ISSUE TITLE
下载不了

### ISSUE THREAD

**Issue by chch715** [PyJun/Mooc_Downloader#33]
这个版本任何资源都下载不了

**Comment by SupremeWolf** [comment]
可能是UA的原因，你可以修改试试。
把**Mooc_Config.py**中的 _aira2_cmd_ 变量修改为：
`aira2_cmd = '%s --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36 -- fUcIvJ01pZVQhNq23lXm9gjazkeonsCx" --check-certificate=false -x 16 -s 64 -j 64 -k 2M --disk-cache 128M --max-overall-download-limit %s "{url:}" -d "{dirname:}" -o "{filename:}"'%(aria2_path, download_speed)`

相关：
#32 
#28

**Comment by banjiaojuhao** [comment]
试试我的[fork](https://github.com/banjiaojuhao/Mooc_Downloader-NoSpeedLimit)，看看能不能解决你的问题
