### ISSUE TITLE
可以下载自己购买的网易云课堂嘛

### ISSUE THREAD

**Issue by guoyida** [PyJun/Mooc_Downloader#34]
自己买了课程，好像收费课程即使是买了部分课时也是加密的，还强制去APP里观看，不想用APP，不知道能不能下载加密的已购课程

**Comment by PyJun** [comment]
VIP可以


 
---原始邮件---
发件人: "guoyida"<notifications@github.com&gt;
发送时间: 2020年5月29日 21:49:56
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [PyJun/Mooc_Downloader] 可以下载自己购买的网易云课堂嘛 (#34)




 
自己买了课程，好像收费课程即使是买了部分课时也是加密的，还强制去APP里观看，不想用APP，不知道能不能下载加密的已购课程
