### ISSUE TITLE
天亮了，雨停了，它又行了

### ISSUE THREAD

**Issue by yjg5035** [PyJun/Mooc_Downloader#35]

**Comment by StephenSHX** [comment]
我也遇到了这个问题，下载的都是pdf还有srt字幕文件

**Comment by PyJun** [comment]
用releases里的最新版的安装包，
源码已经好久没更新了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "StephenSHX"<notifications@github.com&gt;; 
发送时间: 2020年6月13日(星期六) 上午10:48
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [PyJun/Mooc_Downloader] 天亮了，雨停了，它又行了 (#35)





 
我也遇到了这个问题，下载的都是pdf还有srt字幕文件

**Comment by StephenSHX** [comment]
源码还会继续更新吗，大佬



---原始邮件---
发件人: "PyJun"<notifications@github.com&gt;
发送时间: 2020年6月13日(周六) 上午10:50
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"StephenSHX"<shi_haoxin@qq.com&gt;;
主题: Re: [PyJun/Mooc_Downloader] 天亮了，雨停了，它又行了 (#35)




 用releases里的最新版的安装包， 
 源码已经好久没更新了 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "StephenSHX"<notifications@github.com&amp;gt;;  
 发送时间: 2020年6月13日(星期六) 上午10:48 
 收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&amp;gt;;  
 抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;;  
 主题: Re: [PyJun/Mooc_Downloader] 天亮了，雨停了，它又行了 (#35) 
 
 
 
 
 
   
 我也遇到了这个问题，下载的都是pdf还有srt字幕文件

**Comment by kanhao100** [comment]
源码还会继续更新吗，大佬

**Comment by banjiaojuhao** [comment]
作者毕竟是要恰饭的，不可能要求人家用爱发电。也可以看看我的[fork](https://github.com/banjiaojuhao/Mooc_Downloader-NoSpeedLimit)，有时间会修bug
