### ISSUE TITLE
对于旧版本该如何卸载？发现不是覆盖安装

### ISSUE THREAD

**Issue by SomaHaruto** [PyJun/Mooc_Downloader#37]
每一次发布新版本，旧版本要怎么卸载掉呢？或者能不能考虑改成将新版本在旧版本的基础上覆盖安装，另外，下载课件为啥只有PDF格式可选，不能下载它的原版格式吗？因为发现PDF格式转码有问题呀，一些包含公式的源文档，下载器下载下的PDF里会有乱码……

**Comment by PyJun** [comment]
最新版已支持增量更新




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"SomaHaruto"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月28日(星期天) 凌晨1:58
收件人:&nbsp;"PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[PyJun/Mooc_Downloader] 对于旧版本该如何卸载？发现不是覆盖安装 (#37)





 
每一次发布新版本，旧版本要怎么卸载掉呢？或者能不能考虑改成将新版本在旧版本的基础上覆盖安装，另外，下载课件为啥只有PDF格式可选，不能下载它的原版格式吗？因为发现PDF格式转码有问题呀，一些包含公式的源文档，下载器下载下的PDF里会有乱码……
