### ISSUE TITLE
视频资源无法下载(已解决, 突然又好了...)

### ISSUE THREAD

**Issue by leon9dragon** [PyJun/Mooc_Downloader#38]
<del>下载网易云课堂视频的时候提示资源无法下载</del>
换了个网络环境, 又能下载了, 不好意思~

**Comment by PyJun** [comment]
反馈一下课程链接



---原始邮件---
发件人: "2TiR3D"<notifications@github.com&gt;
发送时间: 2020年7月1日(周三) 上午9:13
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [PyJun/Mooc_Downloader] 视频资源无法下载 (#38)




 
下载网易云课堂视频的时候提示资源无法下载

**Comment by leon9dragon** [comment]
网络环境问题, 换了又能用了 👍
