### ISSUE TITLE
获取链接

### ISSUE THREAD

**Issue by wula08042** [PyJun/Mooc_Downloader#4]
可不可以加一个仅获取下载链接的选项呢

**Comment by PyJun** [comment]
获取下载链接对用户不友好，
直接下载好更方便，更快捷。
代码我已经开源，你可以在我源码上面修改


 
---原始邮件---
发件人: "wula08042"<notifications@github.com>
发送时间: 2019年8月1日 21:41:32
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [PyJun/Mooc_Downloader] 获取链接 (#4)



可不可以加一个仅获取下载链接的选项呢

**Comment by wula08042** [comment]
> 获取下载链接对用户不友好， 直接下载好更方便，更快捷。 代码我已经开源，你可以在我源码上面修改
> […](#)
> ---原始邮件--- 发件人: "wula08042"<notifications@github.com> 发送时间: 2019年8月1日 21:41:32 收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [PyJun/Mooc_Downloader] 获取链接 (#4) 可不可以加一个仅获取下载链接的选项呢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

吼的
