### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by kmyhy** [PyJun/Mooc_Downloader#42]
输入已付费过的课程地址，比如 https://class.imooc.com/course/1190，提示：视频课程链接不合法，请回车继续...

**Comment by PyJun** [comment]
收到反馈，会更新的



---原始邮件---
发件人: "steven yang"<notifications@github.com&gt;
发送时间: 2020年8月11日(周二) 上午10:47
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [PyJun/Mooc_Downloader] 无法下载 (#42)




 
输入已付费过的课程地址，比如 https://class.imooc.com/course/1190，提示：视频课程链接不合法，请回车继续...

**Comment by PyJun** [comment]
> 输入已付费过的课程地址，比如 [https://class.imooc.com/course/1190，提示：视频课程链接不合法，请回车继续](https://class.imooc.com/course/1190%EF%BC%8C%E6%8F%90%E7%A4%BA%EF%BC%9A%E8%A7%86%E9%A2%91%E8%AF%BE%E7%A8%8B%E9%93%BE%E6%8E%A5%E4%B8%8D%E5%90%88%E6%B3%95%EF%BC%8C%E8%AF%B7%E5%9B%9E%E8%BD%A6%E7%BB%A7%E7%BB%AD)...

现在已经支持了
