### ISSUE TITLE
从哪里获取最新版下载器？

### ISSUE THREAD

**Issue by my3jie** [PyJun/Mooc_Downloader#43]

**Comment by PyJun** [comment]
http://xuewuzhi.cn/downloader
从这里下载最新版



---原始邮件---
发件人: "bruce"<notifications@github.com&gt;
发送时间: 2020年8月11日(周二) 晚上8:06
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [PyJun/Mooc_Downloader] win10 安装最新版，然后总说网络连接出错， (#43)
