### ISSUE TITLE
吴恩达的微专业课程不支持下载

### ISSUE THREAD

**Issue by TomeOkin** [PyJun/Mooc_Downloader#48]
https://mooc.study.163.com/smartSpec/detail/1001319001.htm
https://mooc.study.163.com/learn/2001281002?tid=2001392029#/learn/announce

**Comment by PyJun** [comment]
> https://mooc.study.163.com/smartSpec/detail/1001319001.htm
> https://mooc.study.163.com/learn/2001281002?tid=2001392029#/learn/announce

可以下载的，需要登录网易云账号，而且账号需要提前参与这几门课程
