### ISSUE TITLE
学堂在线无法下载

### ISSUE THREAD

**Issue by ykla** [PyJun/Mooc_Downloader#49]
```
输入一个视频课程网址(q退出, m菜单): https://www.xuetangx.com/course/BJFU01011001735/4230180

视频课程链接不合法！请输入包含以下网址前缀的链接！
```

**Comment by TomeOkin** [comment]
得先加入学习，复制加入学习后的地址

**Comment by PyJun** [comment]
先用，next.xuetangx.com，这个域名


 
---原始邮件---
发件人: "FindWaySociety-ykla"<notifications@github.com&gt;
发送时间: 2020年9月11日 14:49:53
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [PyJun/Mooc_Downloader] 学堂在线无法下载 (#49)




 输入一个视频课程网址(q退出, m菜单): https://www.xuetangx.com/course/BJFU01011001735/4230180 视频课程链接不合法！请输入包含以下网址前缀的链接！

**Comment by ykla** [comment]
next.xuetangx.com可用。
