### ISSUE TITLE
请问账号已购的mooc课程，支持下载么？

### ISSUE THREAD

**Issue by SugarsL** [PyJun/Mooc_Downloader#5]
自己有账号，已购买一些课程。能用该工具进行批量下载么？

**Comment by PyJun** [comment]
可以下载


 
---原始邮件---
发件人: "SugarsL"<notifications@github.com>
发送时间: 2019年8月20日 10:48:00
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [PyJun/Mooc_Downloader] 请问账号已购的mooc课程，支持下载么？ (#5)



自己有账号，已购买一些课程。能用该工具进行批量下载么？

**Comment by PyJun** [comment]
群里有工具


 
---原始邮件---
发件人: "SugarsL"<notifications@github.com>
发送时间: 2019年8月20日 10:48:00
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [PyJun/Mooc_Downloader] 请问账号已购的mooc课程，支持下载么？ (#5)



自己有账号，已购买一些课程。能用该工具进行批量下载么？

**Comment by xiaosTyy** [comment]
群号是多少？

**Comment by xiaoyaoyuxin** [comment]
求入群

**Comment by PyJun** [comment]
> 自己有账号，已购买一些课程。能用该工具进行批量下载么？

可以，升级为SVIP用户后，支持下载已购课程

**Comment by C4az6** [comment]
海量盗版网课学习平台，为学生党而生：youkewang.top
