### ISSUE TITLE
无法下载，提示“ 视频课程链接不合法！请重新输入! ”

### ISSUE THREAD

**Issue by qiqi925** [PyJun/Mooc_Downloader#51]
下载中国大学MOOC，总是提示“ 视频课程链接不合法！请重新输入! ”

无法下载，之前 1.8.8没有这个问题。 新的1.9.1重新安装也是同样的问题。

这是我使用的链接
https://www.icourse163.org/learn/BLCU-1003467013?tid=1461488444#/learn/content

请麻烦看看，谢谢

**Comment by lieutenant-liu** [comment]
律师函的问题

**Comment by qiqi925** [comment]
> 律师函的问题

我没明白，请具体说说解决方法，如果有的话，谢谢

**Comment by PyJun** [comment]
> 下载中国大学MOOC，总是提示“ 视频课程链接不合法！请重新输入! ”
> 
> 无法下载，之前 1.8.8没有这个问题。 新的1.9.1重新安装也是同样的问题。
> 
> 这是我使用的链接
> https://www.icourse163.org/learn/BLCU-1003467013?tid=1461488444#/learn/content
> 
> 请麻烦看看，谢谢

你好，现在可以了
