### ISSUE TITLE
为什么mooc下载只下载了pdf，不下载视频，

### ISSUE THREAD

**Issue by 2236133143** [PyJun/Mooc_Downloader#52]

**Comment by peter-wang321** [comment]
+1

**Comment by PyJun** [comment]
用最新版的学无止下载器，直接百度“学无止下载”，然后安装



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "peter-wang321"<notifications@github.com&gt;; 
发送时间: 2020年12月24日(星期四) 凌晨1:53
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [PyJun/Mooc_Downloader] 为什么mooc下载只下载了pdf，不下载视频， (#52)





 
+1
