### ISSUE TITLE
v1.9.2版本网易云课堂下载报错

### ISSUE THREAD

**Issue by zzgit00** [PyJun/Mooc_Downloader#56]
输入一个视频课程网址(q退出, m菜单): https://study.163.com/course/courseLearn.htm?courseId=1004573006#/learn/video?lessonId=1279239037&courseId=1004573006
您未登录，是否登录网易云课程[y/(n)]: y

程序异常退出，请重新打开再次尝试，若仍未解决，请反馈作者！
请按任意键继续. . .

**Comment by PyJun** [comment]
重装下软件



---原始邮件---
发件人: "zzgit00"<notifications@github.com&gt;
发送时间: 2021年1月7日(周四) 晚上7:50
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [PyJun/Mooc_Downloader] v1.9.2版本网易云课堂下载报错 (#56)




 
输入一个视频课程网址(q退出, m菜单): https://study.163.com/course/courseLearn.htm?courseId=1004573006#/learn/video?lessonId=1279239037&amp;courseId=1004573006
 您未登录，是否登录网易云课程[y/(n)]: y
 
程序异常退出，请重新打开再次尝试，若仍未解决，请反馈作者！
 请按任意键继续. . .

**Comment by zzgit00** [comment]
重装了也一样

**Comment by zzgit00** [comment]
哥，你这冲了会员下不了就不管了吗？

**Comment by PyJun** [comment]
你好，邮箱反馈一下课程链接，同时发下账号密码，我下次更新软件会修复的

**Comment by PyJun** [comment]
> 输入一个视频课程网址(q退出, m菜单): https://study.163.com/course/courseLearn.htm?courseId=1004573006#/learn/video?lessonId=1279239037&courseId=1004573006
> 您未登录，是否登录网易云课程[y/(n)]: y
> 
> 程序异常退出，请重新打开再次尝试，若仍未解决，请反馈作者！
> 请按任意键继续. . .

邮箱反馈下，附上账号密码，我给你调试下

**Comment by PyJun** [comment]
你好，反馈一下，这门课程的账号密码，我这给你调试下（前段时间实在太忙，没时间处理，不好意思）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PyJun/Mooc_Downloader"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月7日(星期四) 晚上7:50
收件人:&nbsp;"PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[PyJun/Mooc_Downloader] v1.9.2版本网易云课堂下载报错 (#56)





 
输入一个视频课程网址(q退出, m菜单): https://study.163.com/course/courseLearn.htm?courseId=1004573006#/learn/video?lessonId=1279239037&amp;courseId=1004573006
 您未登录，是否登录网易云课程[y/(n)]: y
 
程序异常退出，请重新打开再次尝试，若仍未解决，请反馈作者！
 请按任意键继续. . .

**Comment by zzgit00** [comment]
你好，网易账号绑定的东西比较多，不太方便给出。

**Comment by PyJun** [comment]
Ok，方便qq联系嘛，我私下联系你



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zzgit00"<notifications@github.com&gt;; 
发送时间: 2021年1月23日(星期六) 下午4:32
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;; 
抄送: "PyJun"<py.jun@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [PyJun/Mooc_Downloader] v1.9.2版本网易云课堂下载报错 (#56)





 
你好，网易账号绑定的东西比较多，不太方便给出。

**Comment by zzgit00** [comment]
1109440800

**Comment by PyJun** [comment]
> 输入一个视频课程网址(q退出, m菜单): https://study.163.com/course/courseLearn.htm?courseId=1004573006#/learn/video?lessonId=1279239037&courseId=1004573006
> 您未登录，是否登录网易云课程[y/(n)]: y
> 
> 程序异常退出，请重新打开再次尝试，若仍未解决，请反馈作者！
> 请按任意键继续. . .

下载最新版软件就解决了
