### ISSUE TITLE
SVIP用户无法下载网易云已购买课程

### ISSUE THREAD

**Issue by kellen5l** [PyJun/Mooc_Downloader#62]
下载器内登录已购买课程的账号，下载时提示无权限下载

**Comment by CLccxx** [comment]
同问 请问有解决吗 ？换电脑登录错设备了

**Comment by xlinboy** [comment]
同问 请问有解决吗

**Comment by PyJun** [comment]
课程链接发下哈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月21日(周一) 晚上6:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [PyJun/Mooc_Downloader] SVIP用户无法下载网易云已购买课程 (#62)




 
同问 请问有解决吗

**Comment by PyJun** [comment]
最新版已经支持网易云课堂下载
