### ISSUE TITLE
为什么有些课程有视频资源，却只能下载PDF课件呢？

### ISSUE THREAD

**Issue by BinGitGuoHubBJTU** [PyJun/Mooc_Downloader#7]
谢谢您的开发！可是为什么有些课程明明有视频资源，可是程序只能下载PDF课件呢？

**Comment by mz121** [comment]
> 谢谢您的开发！可是为什么有些课程明明有视频资源，可是程序只能下载PDF课件呢？

我也遇到这样的问题，不知为何。

**Comment by PyJun** [comment]
请使用最新版
下载地址: https://github.com/PyJun/Mooc_Downloader/releases


 
---原始邮件---
发件人: "mz121"<notifications@github.com&gt;
发送时间: 2019年11月21日 21:50:47
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [PyJun/Mooc_Downloader] 为什么有些课程有视频资源，却只能下载PDF课件呢？ (#7)


 
谢谢您的开发！可是为什么有些课程明明有视频资源，可是程序只能下载PDF课件呢？
  
我也遇到这样的问题，不知为何。

**Comment by runck** [comment]
使用最新版（1.50版本）python脚本运行也出现同样问题。例如这个课程中有若干周都只下载了pdf，https://www.icourse163.org/learn/BIT-1001871001。不知是自己环境问题，还是其他原因。

**Comment by PyJun** [comment]
没问题，你用exe文件，别用python源码运行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "runck"<notifications@github.com&gt;; 
发送时间: 2020年2月8日(星期六) 中午1:52
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;; 
抄送: "PyJun"<py.jun@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [PyJun/Mooc_Downloader] 为什么有些课程有视频资源，却只能下载PDF课件呢？ (#7)




使用最新版（1.50版本）python脚本运行也出现同样问题。例如这个课程中有若干周都只下载了pdf，https://www.icourse163.org/learn/BIT-1001871001。不知是自己环境问题，还是其他原因。

**Comment by runck** [comment]
> 没问题，你用exe文件，别用python源码运行

谢谢您的回复，不知exe就是其下Assets的源码打包结果吗？主要源码包只有6M左右，而链接网盘里exe有60M加需要安装，感觉还是运行源码方便。如果exe就是同一源码打包，我再检查下是否是本机环境问题。

**Comment by ZHANGYIZHOU1999** [comment]
您好，我也遇到类似的问题，我下载的一个课程只能下载pdf文件，另一个课程没有课件，只创建了一堆课件（也没有报错提示网络问题之类的）。用的是最新版1.5.0版本，exe和源码都试过，结果都一样。
请问有什么解决办法吗？谢谢。

**Comment by PyJun** [comment]
截图反馈一下，还有课程链接




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ZHANGYIZHOU1999"<notifications@github.com&gt;; 
发送时间: 2020年3月3日(星期二) 晚上8:21
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;; 
抄送: "PyJun"<py.jun@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [PyJun/Mooc_Downloader] 为什么有些课程有视频资源，却只能下载PDF课件呢？ (#7)




您好，我也遇到类似的问题，我下载的一个课程只能下载pdf文件，另一个课程没有课件，只创建了一堆课件（也没有报错提示网络问题之类的）。用的是最新版1.5.0版本，exe和源码都试过，结果都一样。
 请问有什么解决办法吗？谢谢。

**Comment by ZHANGYIZHOU1999** [comment]
您好
只有视频没有课件的课程：
https://www.icourse163.org/learn/RUC-1449339163#/learn/announce
有课件有视频，只能下载视频的课程：
https://www.icourse163.org/learn/BIT-268001?tid=1207014257#/learn/announce









------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"PyJun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月3日(星期二) 晚上8:30
收件人:&nbsp;"PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送:&nbsp;"邹颐彰"<1320607042@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [PyJun/Mooc_Downloader] 为什么有些课程有视频资源，却只能下载PDF课件呢？ (#7)



截图反馈一下，还有课程链接 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "ZHANGYIZHOU1999"<notifications@github.com&amp;gt;;  
 发送时间: 2020年3月3日(星期二) 晚上8:21 
 收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&amp;gt;;  
 抄送: "PyJun"<py.jun@qq.com&amp;gt;; "Comment"<comment@noreply.github.com&amp;gt;;  
 主题: Re: [PyJun/Mooc_Downloader] 为什么有些课程有视频资源，却只能下载PDF课件呢？ (#7) 
 
 
 
 
 您好，我也遇到类似的问题，我下载的一个课程只能下载pdf文件，另一个课程没有课件，只创建了一堆课件（也没有报错提示网络问题之类的）。用的是最新版1.5.0版本，exe和源码都试过，结果都一样。 
  请问有什么解决办法吗？谢谢。

**Comment by ZHANGYIZHOU1999** [comment]
https://www.icourse163.org/course/NWU-1002328025?tid=1207118201&from=study
这几天发现这个连接可以下载视频，我之前给的两个仍然不行

**Comment by deanfu** [comment]
已经用了最新版了，下载不了视频
https://www.icourse163.org/course/tufc-1206039802?tid=1206345201

就能下载一个空目录，截不了图，空目录内容如下
 E:\temp\商业银行经营学__上海财经大学 的目录

2020/03/26  23:38    <DIR>          .
2020/03/26  23:38    <DIR>          ..
2020/02/25  11:42    <DIR>          {1}--课程
               0 个文件              0 字节

 E:\temp\商业银行经营学__上海财经大学\{1}--课程 的目录

2020/02/25  11:42    <DIR>          .
2020/02/25  11:42    <DIR>          ..
2020/02/25  11:42    <DIR>          {10}--第十章国际业务
2020/02/25  11:42    <DIR>          {11}--第十一章商业银行资产负债管理策略
2020/02/25  11:42    <DIR>          {12}--第十二章商业银行绩效评估
2020/02/25  11:42    <DIR>          {13}--第十三章商业银行经营风险和内部控制
2020/02/25  11:42    <DIR>          {14}--第十四章商业银行经营发展趋势
2020/02/25  11:41    <DIR>          {1}--第一章导论
2020/02/25  11:41    <DIR>          {2}--第二章商业银行资本
2020/02/25  11:41    <DIR>          {3}--第三章负债业务的经营管理
2020/02/25  11:41    <DIR>          {4}--第四章现金资产业务
2020/02/25  11:42    <DIR>          {5}--第五章贷款业务管理
2020/02/25  11:42    <DIR>          {6}--第六章银行证券投资业务
2020/02/25  11:42    <DIR>          {7}--第七章租赁和信托
2020/02/25  11:42    <DIR>          {8}--第八章表外业务
2020/02/25  11:42    <DIR>          {9}--第九章其他业务
               0 个文件              0 字节

 E:\temp\商业银行经营学__上海财经大学\{1}--课程\{10}--第十章国际业务 的目录

2020/02/25  11:42    <DIR>          .
2020/02/25  11:42    <DIR>          ..
2020/02/25  11:42    <DIR>          {1}--10-1-1国际业务的经营目标与组织机构
2020/02/25  11:42    <DIR>          {2}--10-2-1外汇资金筹集
2020/02/25  11:42    <DIR>          {3}--10-3-1贸易融资与国际贷款（一）
2020/02/25  11:42    <DIR>          {4}--10-3-2贸易融资与国际贷款（二）
2020/02/25  11:42    <DIR>          {5}--10-3-3贸易融资与国际贷款（三）
2020/02/25  11:42    <DIR>          {6}--10-4-1外汇买卖（一）
2020/02/25  11:42    <DIR>          {7}--10-4-2外汇买卖（二）
2020/02/25  11:42    <DIR>          {8}--10-5-1离岸金融业务
               0 个文件              0 字节

 E:\temp\商业银行经营学__上海财经大学\{1}--课程\{10}--第十章国际业务\{1}--10-1-1国际业务的经营目标与组织机构 的目录

2020/02/25  11:42    <DIR>          .
2020/02/25  11:42    <DIR>          ..
               0 个文件              0 字节

**Comment by PyJun** [comment]
现在最新版是1.5.3，截图反馈一下呗


 
---原始邮件---
发件人: "deanfu"<notifications@github.com&gt;
发送时间: 2020年3月26日 23:41:21
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "PyJun"<py.jun@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [PyJun/Mooc_Downloader] 为什么有些课程有视频资源，却只能下载PDF课件呢？ (#7)




 
已经用了最新版了，下载不了视频
 https://www.icourse163.org/course/tufc-1206039802?tid=1206345201
 
就能下载一个空目录，截不了图，空目录内容如下
 E:\temp\商业银行经营学__上海财经大学 的目录
 
2020/03/26  23:38    
          .
 2020/03/26  23:38              ..
 2020/02/25  11:42              {1}--课程
 0 个文件              0 字节

 
E:\temp\商业银行经营学__上海财经大学{1}--课程 的目录
 
2020/02/25  11:42    
          .
 2020/02/25  11:42              ..
 2020/02/25  11:42              {10}--第十章国际业务
 2020/02/25  11:42              {11}--第十一章商业银行资产负债管理策略
 2020/02/25  11:42              {12}--第十二章商业银行绩效评估
 2020/02/25  11:42              {13}--第十三章商业银行经营风险和内部控制
 2020/02/25  11:42              {14}--第十四章商业银行经营发展趋势
 2020/02/25  11:41              {1}--第一章导论
 2020/02/25  11:41              {2}--第二章商业银行资本
 2020/02/25  11:41              {3}--第三章负债业务的经营管理
 2020/02/25  11:41              {4}--第四章现金资产业务
 2020/02/25  11:42              {5}--第五章贷款业务管理
 2020/02/25  11:42              {6}--第六章银行证券投资业务
 2020/02/25  11:42              {7}--第七章租赁和信托
 2020/02/25  11:42              {8}--第八章表外业务
 2020/02/25  11:42              {9}--第九章其他业务
 0 个文件              0 字节

 
E:\temp\商业银行经营学__上海财经大学{1}--课程{10}--第十章国际业务 的目录
 
2020/02/25  11:42    
          .
 2020/02/25  11:42              ..
 2020/02/25  11:42              {1}--10-1-1国际业务的经营目标与组织机构
 2020/02/25  11:42              {2}--10-2-1外汇资金筹集
 2020/02/25  11:42              {3}--10-3-1贸易融资与国际贷款（一）
 2020/02/25  11:42              {4}--10-3-2贸易融资与国际贷款（二）
 2020/02/25  11:42              {5}--10-3-3贸易融资与国际贷款（三）
 2020/02/25  11:42              {6}--10-4-1外汇买卖（一）
 2020/02/25  11:42              {7}--10-4-2外汇买卖（二）
 2020/02/25  11:42              {8}--10-5-1离岸金融业务
 0 个文件              0 字节

 
E:\temp\商业银行经营学__上海财经大学{1}--课程{10}--第十章国际业务{1}--10-1-1国际业务的经营目标与组织机构 的目录
 
2020/02/25  11:42    
          .
 2020/02/25  11:42              ..
 0 个文件              0 字节

**Comment by ZHANGYIZHOU1999** [comment]
你好，我说的两个连接依然存在这样的问题，1.5.3版本也是这样。

邹颐彰
zou_yizhang1103@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"PyJun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 晚上11:51
收件人:&nbsp;"PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送:&nbsp;"邹颐彰"<1320607042@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [PyJun/Mooc_Downloader] 为什么有些课程有视频资源，却只能下载PDF课件呢？ (#7)





 现在最新版是1.5.3，截图反馈一下呗 
 
 
   
 ---原始邮件--- 
 发件人: "deanfu"<notifications@github.com&amp;gt; 
 发送时间: 2020年3月26日 23:41:21 
 收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&amp;gt;; 
 抄送: "PyJun"<py.jun@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题: Re: [PyJun/Mooc_Downloader] 为什么有些课程有视频资源，却只能下载PDF课件呢？ (#7) 
 
 
 
 
   
 已经用了最新版了，下载不了视频 
  https://www.icourse163.org/course/tufc-1206039802?tid=1206345201 
   
 就能下载一个空目录，截不了图，空目录内容如下 
  E:\temp\商业银行经营学__上海财经大学 的目录 
   
 2020/03/26  23:38     
           . 
  2020/03/26  23:38              .. 
  2020/02/25  11:42              {1}--课程 
  0 个文件              0 字节 
 
   
 E:\temp\商业银行经营学__上海财经大学{1}--课程 的目录 
   
 2020/02/25  11:42     
           . 
  2020/02/25  11:42              .. 
  2020/02/25  11:42              {10}--第十章国际业务 
  2020/02/25  11:42              {11}--第十一章商业银行资产负债管理策略 
  2020/02/25  11:42              {12}--第十二章商业银行绩效评估 
  2020/02/25  11:42              {13}--第十三章商业银行经营风险和内部控制 
  2020/02/25  11:42              {14}--第十四章商业银行经营发展趋势 
  2020/02/25  11:41              {1}--第一章导论 
  2020/02/25  11:41              {2}--第二章商业银行资本 
  2020/02/25  11:41              {3}--第三章负债业务的经营管理 
  2020/02/25  11:41              {4}--第四章现金资产业务 
  2020/02/25  11:42              {5}--第五章贷款业务管理 
  2020/02/25  11:42              {6}--第六章银行证券投资业务 
  2020/02/25  11:42              {7}--第七章租赁和信托 
  2020/02/25  11:42              {8}--第八章表外业务 
  2020/02/25  11:42              {9}--第九章其他业务 
  0 个文件              0 字节 
 
   
 E:\temp\商业银行经营学__上海财经大学{1}--课程{10}--第十章国际业务 的目录 
   
 2020/02/25  11:42     
           . 
  2020/02/25  11:42              .. 
  2020/02/25  11:42              {1}--10-1-1国际业务的经营目标与组织机构 
  2020/02/25  11:42              {2}--10-2-1外汇资金筹集 
  2020/02/25  11:42              {3}--10-3-1贸易融资与国际贷款（一） 
  2020/02/25  11:42              {4}--10-3-2贸易融资与国际贷款（二） 
  2020/02/25  11:42              {5}--10-3-3贸易融资与国际贷款（三） 
  2020/02/25  11:42              {6}--10-4-1外汇买卖（一） 
  2020/02/25  11:42              {7}--10-4-2外汇买卖（二） 
  2020/02/25  11:42              {8}--10-5-1离岸金融业务 
  0 个文件              0 字节 
 
   
 E:\temp\商业银行经营学__上海财经大学{1}--课程{10}--第十章国际业务{1}--10-1-1国际业务的经营目标与组织机构 的目录 
   
 2020/02/25  11:42     
           . 
  2020/02/25  11:42              .. 
  0 个文件              0 字节

**Comment by ShuiHuo** [comment]
部分课程视频没能下载，只会创建一系列目录，如：
https://www.icourse163.org/learn/XJTU-1002838006

临时解决方法是用 [Video DownloadHelper](https://www.downloadhelper.net/) 一个一个下载然后重命名和放到对应目录。

**Comment by PyJun** [comment]
用最新版学无止下载器



---原始邮件---
发件人: "水货"<notifications@github.com&gt;
发送时间: 2020年4月7日(周二) 晚上6:34
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "PyJun"<py.jun@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [PyJun/Mooc_Downloader] 为什么有些课程有视频资源，却只能下载PDF课件呢？ (#7)




 
部分课程视频没能下载，只会创建一系列目录，如：
 https://www.icourse163.org/learn/XJTU-1002838006
 
临时解决方法是用 Video DownloadHelper 一个一个下载然后重命名和放到对应目录。

**Comment by CaesarSmith** [comment]
您好，我昨天也是遇到了用exe能下载，但是运行源码只能下载到PDF的问题，想问下这个是因为环境的问题还是开源的代码里做了限制，如果是做了限制的话我就去研究一下大佬的代码(最近刚好学了点儿爬虫，膜拜一下大佬)

**Comment by CaesarSmith** [comment]
> 
> 
> 您好，我昨天也是遇到了用exe能下载，但是运行源码只能下载到PDF的问题，想问下这个是因为环境的问题还是开源的代码里做了限制，如果是做了限制的话我就去研究一下大佬的代码(最近刚好学了点儿爬虫，膜拜一下大佬)

看了一下，是不是开源代码里的请求接口被屏蔽了，返回的视频链接为空。。。大佬可否共享一下接口，https抓包搞了好久都没弄好.......
# 请求代码：
`url = 'https://www.icourse163.org/dwr/call/plaincall/CourseBean.getLessonUnitLearnVo.dwr'
parse_data = {
        'callCount': '1', 
        'scriptSessionId': '${scriptSessionId}190',
        'c0-scriptName':'CourseBean',
        'c0-methodName':'getLessonUnitLearnVo', 
        'httpSessionId':'5531d06316b34b9486a6891710115ebc',
        'c0-id': '0', 
        'c0-param0':None, #'number:'+meta[0],
        'c0-param1':None, #'number:'+meta[1], 
        'c0-param2':'number:0',
        'c0-param3':None, #'number:'+meta[2], 
        'batchId': '1543633161622'
}
param = ('1215557097', '1', '1217710031')
parse_data['c0-param0'] = param[0]
parse_data['c0-param1'] = param[1]
parse_data['c0-param3'] = param[2]
rsp = requests.post(url, data=parse_data, headers=headers)
rsp.content.decode('unicode_escape')`
# 服务器响应
`'//#DWR-INSERT\n//#DWR-REPLY\nvar s0={};s0.clientEncryptKeyVersion=null;s0.duration=609;s0.encrypt=false;s0.flvCaption=null;s0.flvHdUrl=null;s0.flvSdUrl=null;s0.flvShdUrl=null;s0.isEncrypt=false;s0.key="99ed7479ee303d1b1361b0ee5a4abcee75470a412f2c7fed4c50d7972d4914cde4dd30110d1f85acb040146a7c5af74b817c683222c12d8a109effea0181c8b60015e48ffc49c659b128bfe612dda086d65894b8ef217f1626539e3c9eb40879c29b730d22bdcadb1b4f67996129275fa4c38c6336120510aea1ae1790819de86e0fa3e09eeabea1b068b3d9b9b6597acf0c219eb000a69c12ce9d568813365b3e099fcdb77c69ca7cd6141d92c122af";s0.m3u8HdSize=null;s0.m3u8HdUrl=null;s0.m3u8SdSize=null;s0.m3u8SdUrl=null;s0.m3u8ShdSize=null;s0.m3u8ShdUrl=null;s0.mp4Caption=null;s0.mp4HdUrl=null;s0.mp4SdUrl=null;s0.mp4ShdUrl=null;s0.needKeyTimeValidate=false;s0.playerCollection=3;s0.signature=null;s0.srtKeys=null;s0.start=0;s0.status=null;s0.videoDecryptData=null;s0.videoId=1215557097;s0.videoImgUrl="http://nos.netease.com/mooc-video/9c3559b8-6576-43bd-9595-e810e25d3030.jpg";s0.videoProtectedDataDto=null;\r\ndwr.engine._remoteHandleCallback(\'1543633161622\',\'0\',{contentId:null,contentType:null,duration:null,hdMp4Url:null,htmlContent:null,id:null,learnedPosition:1,origSrtUrl:null,paper:null,parsedSrtUrl:null,post:null,randomKey:null,sdMp4Url:null,shdMp4Url:null,srtKeys:null,textOrigUrl:"",textPageWhRatio:null,textPages:0,textUrl:"",type:null,unitId:null,videoHDUrl:null,videoId:null,videoImgUrl:null,videoLearnTime:0,videoSHDUrl:null,videoUrl:null,videoVo:s0});\n'`

**Comment by CaesarSmith** [comment]
> 
> 
> 您好，我昨天也是遇到了用exe能下载，但是运行源码只能下载到PDF的问题，想问下这个是因为环境的问题还是开源的代码里做了限制，如果是做了限制的话我就去研究一下大佬的代码(最近刚好学了点儿爬虫，膜拜一下大佬)

看了一下，是不是开源代码里的请求接口被屏蔽了，返回的视频链接为空。。。大佬可否共享一下接口，https抓包搞了好久都没弄好.......

_请求代码_：
'''
url = 'https://www.icourse163.org/dwr/call/plaincall/CourseBean.getLessonUnitLearnVo.dwr'
parse_data = {
        'callCount': '1', 
        'scriptSessionId': '${scriptSessionId}190',
        'c0-scriptName':'CourseBean',
        'c0-methodName':'getLessonUnitLearnVo', 
        'httpSessionId':'5531d06316b34b9486a6891710115ebc',
        'c0-id': '0', 
        'c0-param0':None, #'number:'+meta[0],
        'c0-param1':None, #'number:'+meta[1], 
        'c0-param2':'number:0',
        'c0-param3':None, #'number:'+meta[2], 
        'batchId': '1543633161622'
}
param = ('1215557097', '1', '1217710031')
parse_data['c0-param0'] = param[0]
parse_data['c0-param1'] = param[1]
parse_data['c0-param3'] = param[2]
rsp = requests.post(url, data=parse_data, headers=headers)
rsp.content.decode('unicode_escape')
'''
_服务器响应_
`
'//#DWR-INSERT\n//#DWR-REPLY\nvar s0={};s0.clientEncryptKeyVersion=null;s0.duration=609;s0.encrypt=false;s0.flvCaption=null;s0.flvHdUrl=null;s0.flvSdUrl=null;s0.flvShdUrl=null;s0.isEncrypt=false;s0.key="99ed7479ee303d1b1361b0ee5a4abcee75470a412f2c7fed4c50d7972d4914cde4dd30110d1f85acb040146a7c5af74b817c683222c12d8a109effea0181c8b60015e48ffc49c659b128bfe612dda086d65894b8ef217f1626539e3c9eb40879c29b730d22bdcadb1b4f67996129275fa4c38c6336120510aea1ae1790819de86e0fa3e09eeabea1b068b3d9b9b6597acf0c219eb000a69c12ce9d568813365b3e099fcdb77c69ca7cd6141d92c122af";s0.m3u8HdSize=null;s0.m3u8HdUrl=null;s0.m3u8SdSize=null;s0.m3u8SdUrl=null;s0.m3u8ShdSize=null;s0.m3u8ShdUrl=null;s0.mp4Caption=null;s0.mp4HdUrl=null;s0.mp4SdUrl=null;s0.mp4ShdUrl=null;s0.needKeyTimeValidate=false;s0.playerCollection=3;s0.signature=null;s0.srtKeys=null;s0.start=0;s0.status=null;s0.videoDecryptData=null;s0.videoId=1215557097;s0.videoImgUrl="http://nos.netease.com/mooc-video/9c3559b8-6576-43bd-9595-e810e25d3030.jpg";s0.videoProtectedDataDto=null;\r\ndwr.engine._remoteHandleCallback(\'1543633161622\',\'0\',{contentId:null,contentType:null,duration:null,hdMp4Url:null,htmlContent:null,id:null,learnedPosition:1,origSrtUrl:null,paper:null,parsedSrtUrl:null,post:null,randomKey:null,sdMp4Url:null,shdMp4Url:null,srtKeys:null,textOrigUrl:"",textPageWhRatio:null,textPages:0,textUrl:"",type:null,unitId:null,videoHDUrl:null,videoId:null,videoImgUrl:null,videoLearnTime:0,videoSHDUrl:null,videoUrl:null,videoVo:s0});\n'
`

**Comment by CaesarSmith** [comment]
> 
> 
> > 您好，我昨天也是遇到了用exe能下载，但是运行源码只能下载到PDF的问题，想问下这个是因为环境的问题还是开源的代码里做了限制，如果是做了限制的话我就去研究一下大佬的代码(最近刚好学了点儿爬虫，膜拜一下大佬)
> 
> 看了一下，是不是开源代码里的请求接口被屏蔽了，返回的视频链接为空。。。大佬可否共享一下接口，https抓包搞了好久都没弄好.......
> 
> _请求代码_：
> '''
> url = 'https://www.icourse163.org/dwr/call/plaincall/CourseBean.getLessonUnitLearnVo.dwr'
> parse_data = {
> 'callCount': '1',
> 'scriptSessionId': '${scriptSessionId}190',
> 'c0-scriptName':'CourseBean',
> 'c0-methodName':'getLessonUnitLearnVo',
> 'httpSessionId':'5531d06316b34b9486a6891710115ebc',
> 'c0-id': '0',
> 'c0-param0':None, #'number:'+meta[0],
> 'c0-param1':None, #'number:'+meta[1],
> 'c0-param2':'number:0',
> 'c0-param3':None, #'number:'+meta[2],
> 'batchId': '1543633161622'
> }
> param = ('1215557097', '1', '1217710031')
> parse_data['c0-param0'] = param[0]
> parse_data['c0-param1'] = param[1]
> parse_data['c0-param3'] = param[2]
> rsp = requests.post(url, data=parse_data, headers=headers)
> rsp.content.decode('unicode_escape')
> '''
> _服务器响应_
> `'//#DWR-INSERT\n//#DWR-REPLY\nvar s0={};s0.clientEncryptKeyVersion=null;s0.duration=609;s0.encrypt=false;s0.flvCaption=null;s0.flvHdUrl=null;s0.flvSdUrl=null;s0.flvShdUrl=null;s0.isEncrypt=false;s0.key="99ed7479ee303d1b1361b0ee5a4abcee75470a412f2c7fed4c50d7972d4914cde4dd30110d1f85acb040146a7c5af74b817c683222c12d8a109effea0181c8b60015e48ffc49c659b128bfe612dda086d65894b8ef217f1626539e3c9eb40879c29b730d22bdcadb1b4f67996129275fa4c38c6336120510aea1ae1790819de86e0fa3e09eeabea1b068b3d9b9b6597acf0c219eb000a69c12ce9d568813365b3e099fcdb77c69ca7cd6141d92c122af";s0.m3u8HdSize=null;s0.m3u8HdUrl=null;s0.m3u8SdSize=null;s0.m3u8SdUrl=null;s0.m3u8ShdSize=null;s0.m3u8ShdUrl=null;s0.mp4Caption=null;s0.mp4HdUrl=null;s0.mp4SdUrl=null;s0.mp4ShdUrl=null;s0.needKeyTimeValidate=false;s0.playerCollection=3;s0.signature=null;s0.srtKeys=null;s0.start=0;s0.status=null;s0.videoDecryptData=null;s0.videoId=1215557097;s0.videoImgUrl="http://nos.netease.com/mooc-video/9c3559b8-6576-43bd-9595-e810e25d3030.jpg";s0.videoProtectedDataDto=null;\r\ndwr.engine._remoteHandleCallback(\'1543633161622\',\'0\',{contentId:null,contentType:null,duration:null,hdMp4Url:null,htmlContent:null,id:null,learnedPosition:1,origSrtUrl:null,paper:null,parsedSrtUrl:null,post:null,randomKey:null,sdMp4Url:null,shdMp4Url:null,srtKeys:null,textOrigUrl:"",textPageWhRatio:null,textPages:0,textUrl:"",type:null,unitId:null,videoHDUrl:null,videoId:null,videoImgUrl:null,videoLearnTime:0,videoSHDUrl:null,videoUrl:null,videoVo:s0});\n'`

emmmmm, fiddler搞了好久都没成功，然后折腾wireshark终于搞好了，其他课程不清楚，发现'https://www.icourse163.org/dwr/call/plaincall/CourseBean.getLessonUnitLearnVo.dwr'这个接口页面也仍然用，但是返回的也是空的；然后另外的一个get 报文 /eds/api/v1/vod/video?videoId=xxx&signature=xxx&clientType=1返回了一个m3u8文件，观察了一下发行版的exe，也确实是在下载xxx.ts，所以应该是这个接口没错了, 现在唯一的问题是这个signature是怎么来的，需要学习学习

**Comment by CaesarSmith** [comment]
emmmmm, fiddler搞了好久都没成功，然后折腾wireshark终于搞好了，其他课程不清楚，发现dwr/call/plaincall/CourseBean.getLessonUnitLearnVo.dwr
这个接口页面也仍然用，但是返回的也是空的；然后另外的一个get 报文 /eds/api/v1/vod/video?videoId=xxx&signature=xxx&clientType=1返回了一个m3u8文件，观察了一下发行版的exe，也确实是在下载xxx.ts，所以应该是这个接口没错了, 现在唯一的问题是这个signature是怎么来的，需要学习学习

**Comment by CaesarSmith** [comment]
远程膜拜一下大佬，通过一条条分析报文，终于找到signature的来源了，也顺带学习了一波csrf，膜拜膜拜
