### ISSUE TITLE
无法下载学习通课件和视频 更新了也不行

### ISSUE THREAD

**Issue by Bluky-BlueSkyDream** [PyJun/Mooc_Downloader#75]
![IMG20210419183418.jpg](https://user-images.githubusercontent.com/78255599/115225798-1740c900-a141-11eb-8a03-7ce077f8d314.jpg)
半个多月前就发过邮件 作者一直都没给回复 问题也没解决 买了会员也没用 这几天急用课件 突然就出了这个问题 烦死了

**Comment by PyJun** [comment]
你好，发一下这个课程的链接，我修复一下

**Comment by Bluky-BlueSkyDream** [comment]
https://mooc1-1.chaoxing.com/mycourse/studentcourse?courseId=206251180&clazzid=37158260&enc=b8e48ee19305dcc84d89bed88cb6db77&cpi=99642689&vc=1

**Comment by Bluky-BlueSkyDream** [comment]
我学习通上的所有课程我都下载不了

**Comment by PyJun** [comment]
最新版本已经修复这个问题了
![image](https://user-images.githubusercontent.com/39453044/172315308-13cb562e-f4b7-4738-9a20-e496d414010a.png)
请下载新版本后重试
