### ISSUE TITLE
为什么360报木马病毒？？

### ISSUE THREAD

**Issue by my3jie** [PyJun/Mooc_Downloader#76]
今天下载最新版，可是360 突然报有病毒木马

**Comment by PyJun** [comment]
360一直这样，关掉



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月19日(周一) 晚上10:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PyJun/Mooc_Downloader] 为什么360报木马病毒？？ (#76)




 
今天下载最新版，可是360 突然报有病毒木马

**Comment by Bluky-BlueSkyDream** [comment]
> 360一直这样，关掉
> 
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2021年4月19日(周一) 晚上10:53
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.***&gt;;
> 主题: [PyJun/Mooc_Downloader] 为什么360报木马病毒？？ (#76)
> 
> 
> 
> 
>  
> 今天下载最新版，可是360 突然报有病毒木马
>  
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

有空给新议题回复也不回复我？邮件也不回？买了会员花了钱就是这服务？

**Comment by PyJun** [comment]
安装的时候，建议先关闭360软件
