### ISSUE TITLE
提示  程序异常退出，请联系管理员

### ISSUE THREAD

**Issue by cctyl** [PyJun/Mooc_Downloader#79]
![image](https://user-images.githubusercontent.com/34262992/116814794-14a49180-ab8d-11eb-81bb-825f7142e996.png)
出现了如图所示的问题，下载的课程是 https://mooc1-1.chaoxing.com/mycourse/studentstudy?chapterId=398495696&courseId=217421315&clazzid=38960337&enc=ceab0f034219020f66fe1ab72056cff7

**Comment by PyJun** [comment]
收到，感谢反馈~

**Comment by PyJun** [comment]
最新版本支持下载超星学习通
![image](https://user-images.githubusercontent.com/39453044/172314771-ae9de6b0-059f-4fe2-bc6a-067786d90bba.png)
