### ISSUE TITLE
显示网路异常

### ISSUE THREAD

**Issue by kookiya** [PyJun/Mooc_Downloader#8]
![image](https://user-images.githubusercontent.com/32722805/69393933-7fee0100-0d15-11ea-94ce-413a44eca999.png)
![image](https://user-images.githubusercontent.com/32722805/69394081-e83ce280-0d15-11ea-983d-a07a4ff845d7.png)

**Comment by PyJun** [comment]
请确保使用的是最新版学无止下载器


 
---原始邮件---
发件人: "muxiu23"<notifications@github.com&gt;
发送时间: 2019年11月22日 10:47:50
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [PyJun/Mooc_Downloader] 显示网路异常 (#8)

**Comment by muxiu23** [comment]
> 请确保使用的是最新版学无止下载器
> […](#)
> ---原始邮件--- 发件人: "muxiu23"<notifications@github.com&gt; 发送时间: 2019年11月22日 10:47:50 收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [PyJun/Mooc_Downloader] 显示网路异常 (#8) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
LEL-downloader和MOOC均为最新版，都是同样问题

**Comment by QuinnTian** [comment]
我也是 也是最新版突然显示网络异常

**Comment by QuinnTian** [comment]
我的是打开后直接显示网络异常 是最新版

**Comment by QuinnTian** [comment]
我的是打开后直接显示网络异常 是最新版 @PyJun ![image](https://user-images.githubusercontent.com/29975541/71797944-248c8e00-308b-11ea-855b-78a1170a3d01.png)
