### ISSUE TITLE
单独下载超星课程的课件需要充值会员，充值会员之后提示下载不了！！

### ISSUE THREAD

**Issue by Gangster-new** [PyJun/Mooc_Downloader#81]
![20210529123855](https://user-images.githubusercontent.com/68819333/120058114-1f165600-c07b-11eb-814e-d7be2e07c8c4.png)

**Comment by Gangster-new** [comment]
尝试了很多次，都没有下载成功，希望作者解决！！

**Comment by PyJun** [comment]
超星的部分课程下载会失败，这个bug有待修复，把视频链接发下

**Comment by LHS1998** [comment]
遇到同样的问题，三个超星课程都无法下载！烦请作者解决！
示例地址： https://mooc1.chaoxing.com/course/218170486.html

**Comment by PyJun** [comment]
现在已经解决了
