### ISSUE TITLE
登陆已购买课程的慕课网，下载不了已购买的视频

### ISSUE THREAD

**Issue by youaodu** [PyJun/Mooc_Downloader#82]
https://coding.imooc.com/learn/list/207.html

以开通了svip，并且，以登陆了有该课程的账号，下载时还是提示错误
![image](https://user-images.githubusercontent.com/49941556/120764465-bfbcb800-c54a-11eb-840e-5f54e040abec.png)

**Comment by iiio051031448** [comment]
刚刚我也遇到一样问题了

**Comment by xlinboy** [comment]
我也是，请问一下，是为什么呀，免费的我试了一下，也下载不了

**Comment by PyJun** [comment]
课程链接发下哈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月21日(周一) 上午10:55
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [PyJun/Mooc_Downloader] 登陆已购买课程的慕课网，下载不了已购买的视频 (#82)




 
我也是，请问一下，是为什么呀，免费的我试了一下，也下载不了

**Comment by kellen5l** [comment]
> 我也是，请问一下，是为什么呀，免费的我试了一下，也下载不了

已经解决了，网易云课堂用的保利威加密，在js中拿到key和iv，然后用aes128解密下ts文件就可以

**Comment by xlinboy** [comment]
> 课程链接发下哈
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年6月21日(周一) 上午10:55 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [PyJun/Mooc_Downloader] 登陆已购买课程的慕课网，下载不了已购买的视频 (#82) 我也是，请问一下，是为什么呀，免费的我试了一下，也下载不了 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

这个是我试的网址，https://class.imooc.com/course/1222   https://coding.imooc.com/learn/list/461.html

**Comment by youaodu** [comment]
https://coding.imooc.com/learn/list/207.html  这是我的下载地址，您帮忙看下。需要账号的话，我给您

**Comment by youaodu** [comment]
是慕课网更新了吗？我看免费视频也下载不了了

**Comment by xavi3313** [comment]
好像是更新了，我也都下载不了，不管是免费的还是花钱买了的

**Comment by iiio051031448** [comment]
这个bug准备 啥时候修复呀 大佬

**Comment by xavi3313** [comment]
> 这个bug准备 啥时候修复呀 大佬

前2天已经解决了，现在程序升级到1.96解决了这个问题
