### ISSUE TITLE
无法充值会员

### ISSUE THREAD

**Issue by 1245488569** [PyJun/Mooc_Downloader#84]
无法充值会员？怎么解决啊

**Comment by PyJun** [comment]
重试一下，可以了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月24日(周六) 中午11:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PyJun/Mooc_Downloader] 无法充值会员 (#84)




 
无法充值会员？怎么解决啊
