### ISSUE TITLE
无法下载！！！！！！！！

### ISSUE THREAD

**Issue by BGMjie** [PyJun/Mooc_Downloader#88]
![image](https://user-images.githubusercontent.com/38123875/130491248-edbad5c5-1650-4d1c-9178-c1b5d82dff55.png)
下载不了啊，什么都下不了
https://www.icourses.cn/sCourse/course_6701.html

**Comment by PyJun** [comment]
用新版软件，亲测可以下载：
![image](https://user-images.githubusercontent.com/39453044/172314264-8e0f0fd1-e474-43e2-bd77-d37e044b612b.png)
