### ISSUE TITLE
付费成vip，下载速度还是超不过1M

### ISSUE THREAD

**Issue by ghost** [PyJun/Mooc_Downloader#9]

**Comment by PyJun** [comment]
物理限速了吧，宽带不行😂


 
---原始邮件---
发件人: "tiaoteek"<notifications@github.com&gt;
发送时间: 2020年1月6日 20:12:47
收件人: "PyJun/Mooc_Downloader"<Mooc_Downloader@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [PyJun/Mooc_Downloader] 付费成vip，下载速度还是超不过1M (#9)
